### ISSUE TITLE
wr2 metabug

### ISSUE THREAD

**Issue by glennw** [servo/webrender#312]
A list of things we need to handle for wr2. Some of these are blockers for merging, but many can be left until after that.

### Blockers
- [x] Tidy up the shaders directory - remove unused shaders - 50% done
- [x] 3d transforms - 50% done
- [x] Image stretch size support - mchang working on.
- [x] Angle gradient support - WIP branch - nearly done.
- [x] ~~Box shadow caching~~
- [x] ~~Non-rectangular clip support - gw working on.~~
- [x] Tidy up size of UBO array lengths, based on GPU capabilities
- [x] Support other border styles
- [x] Support irregular border corner radii
- [x] Integrate the other mix-blend-mode / filter shaders.
- [x] Re-add webgl display item support.
- [x] transform issue with b.html sidebar.
- [x] pixel snapping.
- [x] accuracy bug with angle gradients.
- [x] square corners on GH bug (gradient clip?).
- [x] box shadow bug on GH (box shadow clip?).

### Optimization ideas
- [ ] Avoid packing primitives for multiple tiles
- [ ] Run parts of tiling / packing / batching on worker threads
- [ ] Optimize / improve the batching algorithm for the alpha batching strategy
- [ ] Add support for partial tile allocations - optimization for transparent_rects
- [ ] Add support for simple rectangle paths - minimize allocation size
- [ ] Support narrowphase detection during tile assignment - optimization for moire demo
- [ ] Support intra-layer occlusion tests - general optimization
- [ ] Support splitting large rounded rectangles - potential general optimization
- [ ] Consider storing all packed primitives in same structure - potential optimization / simpler code
- [ ] Add support for > 8 blend layers per tile - automate the shader code gen?
- [ ] Support narrow phase tile collision test for 3d transformed / perspective layers.

### Others
- [ ] Anti-aliasing - mrobinson is prototyping this.
- [ ] PoC fast path rendering strategy (suggest background color + text tiles)
- [ ] Re-enable rasterizing glyphs on worker threads
- [ ] Add more fine grained GPU timer queries - to profile various parts of each frame.

**Comment by changm** [comment]
My list, not sure this should be a blocker for wr2 merging, or it might be categorized as "before we decide on wr for gecko".

- [ ] An evaluation of WR on Windows.
- [ ] A better story for non good GPUs
- [ ] Standalone WR tests outside of Servo (I can permacrash today with a simple html page that has a background image).

**Comment by glennw** [comment]
@changm For the non-good GPUs, I'd like to try running WR on top of https://blog.chromium.org/2016/06/universal-rendering-with-swiftshader.html and see what the performance is like.

**Comment by glennw** [comment]
wr2 landed! We can open separate bugs for the remaining optimization work above.
