### ISSUE TITLE
[meta] Mozlando performance issues

### ISSUE THREAD

**Issue by kvark** [servo/webrender#3390]
This is a collection of performance issues @gw3583 and myself came up with at Mozlando 2018:
- [ ] picture caching - #2533
- [ ] extreme batching
  - [ ] render text via the image brush
  - [ ] intern and cache gradients
  - [ ] rendering transparent rectangles via the image brush
  - (as a clean-up) stop tracking the screen space rectangles for batching
- [ ]  rewrite the mix-blend mode to use the existing task tree model with help of the partial picture splitting logic that was introduced for plane ordering in #3131
- [ ]  take advantage of clip mask symmetry
- [ ]  detect opaque borders - #3208 (which got reverted - need to investigate)
- [ ]  persist uploaded VBO data across frame renders
- [ ]  pack vertex formats tighter
- [ ]  switch interned primitive data into structure-of-arrays
- [ ]  render opacity filters via the image brush

**Comment by djg** [comment]
I'm currently working on `switch interned primitive data into structure-of-arrays`. #3385
