### ISSUE TITLE
Blob image re-coordination

### ISSUE THREAD

**Issue by nical** [servo/webrender#3418]
Corresponding gecko bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1494403

## TODO

- [x] move tile ranges/offsets and device coordinates from unsigned to signed
- [ ] (PR #3409) update the tile decomposition algorithm to handle
   - [x] partial tiles on all sides
   - [x] negative tile offsets
   - [x] arbitrary tile origins
- [ ] add the glue in WebRender so that we actually take advantage of the arbitrary tile origins etc. by using the blob's visible rect as the image rect (instead of the blob image's size with always-zero origin) and computing the correct layout offset between the top-left corner of the image display item and the position of the tile with offset `(0, 0)`.
- [x] rebase @Gankro's Gecko side changes (@jrmuizel working on it).
- [ ] write the WebRender code that invalidates the right tiles when blob image's visible area changes (the thing we talked about at the allhands with @mstange).
- [ ] try things out and see what's not working?
