### ISSUE TITLE
[meta] Gecko priorities

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#452]
Needed for standing the layer manager up:
- [x] #498 clipped transforms (https://github.com/servo/servo/issues/13578)
- [x] #405 mask images
- [x] multiple windows

Needed for Gecko chrome
- [x] #879 border-image

Needed for performance measurement:
- [x] #464,  #230 subpixel text

Nice to have early because it's foundational:
- [ ] APZ (#1357)
- [ ] path geometry (#402 depends on this)
- [x] big images (#620)
- [x] external image tiles (#645)
- [x] preserve 3d (#739)

Not urgent, but required for QR MVP:
- [x] radial gradient (#639)
- [x] opacity/scaling (#640)
- [x] more border styles (#641)
- [x] `IOSurface` handling (#642)
- [x] source blending (#643)
- [x] hit testing (#1575)

Needed for passing more reference tests:
- [x] better pixel snapping (#1279)
- [x] sticky positioning (#1277)

Other stuff
- [x] Blur
- [x] Shadow's with different radiii
- [x] text decoration (#1418)
- [ ] 3d border colors
- [ ] colored glyphs (#1273)
- [x] improved texture cache behaviour (#1572)

**Comment by glennw** [comment]
@jrmuizel I've talked to @kvark  briefly about these today. Our plan is that the clipped transforms can be done by using the mask image functionality + the primitive cache task that I am working on now (this allows primitives to specify a render task dependency, e.g. for generating an transformed image mask). I'm going to try and land support for that next week. The image mask stuff can be done now without that.

**Comment by staktrace** [comment]
@jrmuizel It seems like a lot of stuff on this list has been done. It might be good to update the post to mark things that are done.

**Comment by glennw** [comment]
@jrmuizel This could probably do with another update - it looks like a few more of those items are ready now. Or should we close this now that we're trying to keep GH and bugzilla issues in sync?

Things on the list that (I think) are ready now:
 * Source blending
 * Hit testing
 * Blur
 * Shadows with different radii
 * Colored glyphs

**Comment by glennw** [comment]
@jrmuizel Is it worth keeping this open now that we are syncing up with bugzilla bugs?

**Comment by glennw** [comment]
I ticked off Blur, Shadows with different radii, hit testing and source blending.
