### ISSUE TITLE
Support for transformed clip regions

### ISSUE THREAD

**Issue by kvark** [servo/webrender#498]
Can be implemented via the image masking (#445) and temporary cached targets (#485) to record the transformed clip region into the mask image.
Related to #154 and #427. Also - https://github.com/servo/servo/issues/13578

The implementation is split into 3 parts:
- [x] refactor the clip handling (#512)
- [x] off-screen clip mask generation (#556)
- [x] removal of the clip shaders (#556)
- [x] API upgrade to actually support the transformed clips (#595)

**Comment by kvark** [comment]
Done by #595. Further support/improvement will go as separate issues.
