### ISSUE TITLE
[Meta] Bullet-proof WebRender

### ISSUE THREAD

**Issue by nical** [servo/webrender#876]
WebRender doesn't currently have much in the way of handling/recovering from errors. It wouldn't hurt to start talking about this.

Recovering doesn't necessarily mean be able to render the current or next frame properly, but ideally notify that something is not working so that the embedding application can decide what to do (possibly shut down WebRender and fall back to some other rendering mechanism).
Triggering a panic can be in many cases a valid option especially for security sensitive scenarios, but should be a last resort if the situation is common (running low on memory should be considered common). In any case we should never get into a situation where the browser keeps running but nothing shows up on the screen.

I think that we should at least handle:
- [x] Failure to create the Renderer.
- [ ] Failure to render/present frames.
- [ ] Failure to perform a large allocation.
- [ ] Reception of invalid/corrupted data from a content process (for this one, panicking is better than doing nothing, but notifying the embedder is better. In the case of gecko we'd rather kill the content process that sent the invalid data than crash the renderer).
- [ ] Providing useful data for crash-stats in case of a panic (I'm thinking about the gfxCriticalError mechanism we have in gecko).

**Comment by kvark** [comment]
I wouldn't call it bullet-proofing (which assumes the continue of operation after catching a bullet) but rather - make it mentally stable (as in - don't panic!) ;)

**Comment by gw3583** [comment]
I don't think there's much in this report that is actionable - we can open specific bugs for things we want to handle gracefully.
